### PR TITLE
Updating R CMD check Actions

### PR DESCRIPTION
**Pull request by MowahidLatif**
Do not merge until all checks are passed.

### CODE REVIEW

**Comment by MowahidLatif** [comment]
Merge when time is available, all checks have passed!

**Review by aylapear — CHANGES_REQUESTED** [review]
R-CMD-check badge needs to be place at top of .Rmd file with rest of badge. R-CMD-check badge should be the 2nd badge overall. Add the badges start and end tags to the group at the top if that syntax isn't present.

**Comment by aylapear** [comment]
Also can you do another thing on this repo. Please delete the file called pr-commands.yaml in the .github/workflows file. This is an action we never ended up using in the end and can be removed if you notice it.

**Comment by MowahidLatif** [comment]
Please merge this branch. Everything is in order.

**Review by aylapear — CHANGES_REQUESTED** [review]
This doesn't appear to be the right level of checks, please adjust the operating system/version of R to the original better. Looks like you ran check_full when check_standard should be run.

**Comment by MowahidLatif** [comment]
Please merge this branch. Everything is in order.

**Review by aylapear — APPROVED** [review]
Correct checks are being run now, badges in order and old unused action is removed

**Pull request merged**
